# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###
#no-redirect -> https://youtrack.jetbrains.com/issue/WI-20560
#@no-redirect
GET {{protocol-and-host}}/authorize?redirect_uri=http%3A%2F%2Flocalhost%2Fdo-something%23fence-callback
Accept: application/json

### Exchange Authorization Code

POST {{protocol-and-host}}/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=thisReallyCanBeAnythingItDoesNotMatter

### Generate Access Token

POST {{protocol-and-host}}/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token=AnyOldRandomString

###

POST {{protocol-and-host}}/user/credentials/google
Content-Type: application/x-www-form-urlencoded

###

GET {{protocol-and-host}}/user/.well-known/openid-configuration
Accept: application/json

###